version: "3"
services:
  client:
    build:
      context: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  express:
    build:
      context: ./server
    ports:
      - '3001:3001'
      - '9229:9229'
    networks:
      - mern-app
    volumes:
      - ".:/server/app"
      - "/server/app/node_modules"
    command:
      - nodemon
      - --inspect=0.0.0.0:9229
      - server/src/index.js
    environment:
      - PORT=3001
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local